services:

  # api:
  #   build: DPE-Energy-Performance-Analysis-API/.
  #   image: dpe-api:latest  # nom explicite de l'image de l'api # actualiser avec le dernier tag du repos de l'api # recup le nom sur 
  #   container_name: fastapi
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - mongo
  #   environment:
  #     ENVIRONMENT: PROD
  #     DB_HOST: mongo
  #     DB_PORT: 27017 # dans le reseau la db est sur ce port 
  #     DB_USER: dpeapi
  #     DB_PWD: pwddpeapi
  #   networks:
  #     - dpe-network
  #   links:
  #     - mongo

  db:
    image: postgres
    container_name: dpe-dbserver
    restart: always
    ports:
      - "5432:5432"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # ${POSTGRES_PASSWORD} to set into .env file (root)
      POSTGRES_DB: dpedb

  minio:
    image: "minio/minio:latest"
    container_name: dpe-filestorage
    restart: always
    ports:
        - "9000:9000"
        - "8900:8900"
    volumes:
        - ./storage/minio:/data/minio
    environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: password
    command: 'minio server /data/minio --console-address ":8900"'
    healthcheck:
        test:
            - CMD
            - curl
            - '-f'
            - 'http://localhost:9000/minio/health/live'
        retries: 3
        timeout: 5s

  elasticsearch:
    image: "elastic/elasticsearch:8.15.1"
    container_name: dpe-elasticsearch
    environment:
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./storage/elk:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: "kibana:8.15.5"
    container_name: dpe-kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  prefect-server: 
    image: prefecthq/prefect:3-python3.12
    container_name: dpe-prefect-server
    ports:
      - "4200:4200"


volumes:
    minio:
        driver: local