services:

  api:
    image: fereol023/dpe-energy-performance-analysis-api:<tag>
    container_name: dpe-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
      - redis
      - prefect-server
    environment:
      ENV: NOLOCAL
      API_HOST: "0.0.0.0"
      API_PORT: "8000"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      SMTP_SERVER: "smtp.gmail.com"
      SMTP_PORT: "465"
      SMTP_USERNAME: xxxxxxxxxx
      SMTP_PASSWORD: xxxxxxxxxx
      ADMIN_EMAIL: xxxxxxxxxx
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB_NAME: dpedb_v2
      POSTGRES_ADMIN_USERNAME: postgres
      POSTGRES_ADMIN_PASSWORD: password
      POSTGRES_READER_USERNAME: reader
      POSTGRES_READER_PASSWORD: password
      POSTGRES_WRITER_USERNAME: writer
      POSTGRES_WRITER_PASSWORD: password
      S3_ACCESS_KEY: xxxxxxxxxx
      S3_SECRET_KEY: xxxxxxxxxx
      S3_BUCKET_NAME: dpe-storage-v1
      S3_REGION: eu-west
      S3_ENDPOINT_URL: http://minio:9000
      PREFECT_API_URL: http://prefect-server:4200/api
      PATH_LOG_DIR: etl/logs/
      PATH_ARCHIVE_DIR: etl/data/archive/
      PATH_DATA_BRONZE: etl/data/1_bronze/
      PATH_DATA_SILVER: etl/data/2_silver/
      PATH_DATA_GOLD: etl/data/3_gold/
      PATH_FILE_INPUT_ENEDIS_CSV: etl/data/1_bronze/conso_enedis.csv
      SCHEMA_ETL_INPUT_FILEPATH: config/schema_input_data.json
      SCHEMA_SILVER_DATA_FILEPATH: etl/ressources/schemas/schema_silver_data.json
      SCHEMA_GOLDEN_DATA_FILEPATH: config/schema_golden_data.json

  db:
    image: postgres
    container_name: dpe-dbserver
    restart: always
    ports:
      - "5432:5432"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # ${POSTGRES_PASSWORD} to set into .env file (root)
      POSTGRES_DB: dpedb

  minio:
    image: "minio/minio:latest"
    container_name: dpe-filestorage
    restart: always
    ports:
        - "9000:9000"
        - "8900:8900"
    volumes:
        - ./storage/minio:/data/minio
    environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: password
    command: 'minio server /data/minio --console-address ":8900"'
    healthcheck:
        test:
            - CMD
            - curl
            - '-f'
            - 'http://localhost:9000/minio/health/live'
        retries: 3
        timeout: 5s

  prefect-server: 
    image: prefecthq/prefect:3-python3.12
    container_name: dpe-prefect-server
    ports:
      - "4200:4200"
      - "4201:4201" 
    entrypoint: ["prefect", "server", "start"]
    command: ["--host", "0.0.0.0", "--port", "4200"]
    environment:
      PREFECT_API_URL: http://localhost:4200/api
    restart: always

  redis:
    image: redis:7-alpine
    container_name: dpe-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./storage/redis:/data
      
volumes:
    minio:
        driver: local