create_table = """
CREATE TABLE IF NOT EXISTS adresses (
    id_ban VARCHAR PRIMARY KEY,
    _id_ademe VARCHAR DEFAULT 'N/C',
    _type_ban VARCHAR DEFAULT 'N/C',
    adresse_ban_ademe VARCHAR DEFAULT 'N/C',
    adresse_enedis VARCHAR DEFAULT 'N/C',
    city_ban VARCHAR DEFAULT 'N/C',
    citycode_ban VARCHAR DEFAULT 'N/C',
    code_commune_enedis VARCHAR DEFAULT 'N/C',
    code_departement_enedis VARCHAR DEFAULT 'N/C',
    code_iris_enedis VARCHAR DEFAULT 'N/C',
    code_postal_ban_ademe VARCHAR DEFAULT 'N/C',
    code_postal_brut_ademe VARCHAR DEFAULT 'N/C',
    code_region_enedis VARCHAR DEFAULT 'N/C',
    complement_d_adresse_batiment_ademe VARCHAR DEFAULT 'N/C',
    complement_d_adresse_logement_ademe VARCHAR DEFAULT 'N/C',
    coordonnee_cartographique_x_ban_ademe VARCHAR DEFAULT 'N/C',
    coordonnee_cartographique_y_ban_ademe VARCHAR DEFAULT 'N/C',
    full_adress_ban VARCHAR DEFAULT 'N/C',
    full_adress_enedis VARCHAR DEFAULT 'N/C',
    housenumber_ban VARCHAR DEFAULT 'N/C',
    identifiant_ban_ademe VARCHAR DEFAULT 'N/C',
    importance_ban VARCHAR DEFAULT 'N/C',
    label_ban VARCHAR DEFAULT 'N/C',
    lat_ban VARCHAR DEFAULT 'N/C',
    libelle_de_voie_enedis VARCHAR DEFAULT 'N/C',
    lon_ban VARCHAR DEFAULT 'N/C',
    name_ban VARCHAR DEFAULT 'N/C',
    nom_commune_ban_ademe VARCHAR DEFAULT 'N/C',
    nom_commune_enedis VARCHAR DEFAULT 'N/C',
    nom_iris_enedis VARCHAR DEFAULT 'N/C',
    nom_residence_ademe VARCHAR DEFAULT 'N/C',
    nom_rue_ban_ademe VARCHAR DEFAULT 'N/C',
    numero_de_voie_enedis VARCHAR DEFAULT 'N/C',
    postcode_ban VARCHAR DEFAULT 'N/C',
    score_ban VARCHAR DEFAULT 'N/C',
    score_ban_ademe VARCHAR DEFAULT 'N/C',
    statut_geocodage_ademe VARCHAR DEFAULT 'N/C',
    street_ban VARCHAR DEFAULT 'N/C',
    tri_des_adresses_enedis VARCHAR DEFAULT 'N/C',
    type_ban VARCHAR DEFAULT 'N/C',
    x_ban VARCHAR DEFAULT 'N/C',
    y_ban VARCHAR DEFAULT 'N/C',
    zone_climatique_ademe VARCHAR DEFAULT 'N/C',
    FOREIGN KEY (_id_ademe) REFERENCES logements(_id_ademe) ON DELETE CASCADE
)
"""
