create_table = """
CREATE TABLE "logements" (
	batch_id VARCHAR(255),
    _id_ademe VARCHAR(255),
    id_ban VARCHAR(255),
    code_postal_ban_ademe VARCHAR(255) NOT NULL,
    absolute_diff_conso_fin_act DECIMAL,
    absolute_diff_conso_prim_fin DECIMAL,
    conso_kwh_m2 DECIMAL,
    consumption_difference DECIMAL,
    annee_construction_ademe DECIMAL,
    apport_interne_saison_chauffe_ademe DECIMAL,
    apport_solaire_saison_chauffe_ademe DECIMAL,
    besoin_ecs_ademe DECIMAL,
    classe_inertie_batiment_ademe TEXT,
    conso_5_usages_par_m2_ef_ademe DECIMAL,
    conso_5_usages_par_m2_ep_ademe DECIMAL,
    conso_chauffage_generateur_n1_installation_n1_ademe DECIMAL,
    conso_ef_generateur_n1_ecs_n1_ademe DECIMAL,
    cout_ecs_energie_n1_ademe DECIMAL,
    cout_total_5_usages_energie_n1_ademe DECIMAL,
    cout_total_5_usages_energie_n2_ademe DECIMAL,
    deperditions_baies_vitrees_ademe DECIMAL,
    deperditions_murs_ademe DECIMAL,
    deperditions_ponts_thermiques_ademe DECIMAL,
    deperditions_portes_ademe DECIMAL,
    emission_ges_5_usages_par_m2_ademe DECIMAL,
    emission_ges_auxiliaires_ademe DECIMAL,
    emission_ges_chauffage_ademe DECIMAL,
    emission_ges_ecs_ademe DECIMAL,
    emission_ges_ecs_energie_n1_ademe DECIMAL,
    etiquette_dpe_ademe VARCHAR(1),
    etiquette_ges_ademe VARCHAR(1),
    nombre_de_logements_enedis INTEGER,
    numero_de_voie_enedis DECIMAL,
    periode_construction_ademe TEXT,
    qualite_isolation_menuiseries_ademe TEXT,
    surface_habitable_desservie_par_installation_ecs_n1_ademe DECIMAL,
    surface_habitable_logement_ademe DECIMAL,
    type_energie_generateur_n1_ecs_n1_ademe TEXT,
    type_energie_generateur_n1_installation_n1_ademe TEXT,
    type_energie_n1_ademe TEXT,
    type_energie_n2_ademe TEXT,
    type_energie_principale_chauffage_ademe TEXT,
    type_energie_principale_ecs_ademe TEXT,
    type_installation_ecs_ademe TEXT,
    ubat_w_par_m2_k_ademe DECIMAL,
    usage_generateur_n1_ecs_n1_ademe TEXT,
    volume_stockage_generateur_n1_ecs_n1_ademe DECIMAL,    
	PRIMARY KEY("_id_ademe"),
	FOREIGN KEY("code_postal_ban_ademe") REFERENCES "villes"("code_postal_ban_ademe") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY("id_ban") REFERENCES "donnees_geocodage"("id_ban") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY("id_ban") REFERENCES "adresses"("id_ban") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY("id_ban") REFERENCES "donnees_climatiques"("id_ban") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("batch_id", "etiquette_dpe_ademe") REFERENCES "tests_statistiques_dpe"("batch_id", "etiquette_dpe_ademe") ON DELETE CASCADE ON UPDATE CASCADE
);
"""
## FOREIGN KEY("etiquette_dpe_ademe") REFERENCES "tests_statistiques_dpe"("etiquette_dpe_ademe") ON DELETE CASCADE ON UPDATE CASCADE
