name: ghaction-ci-volt-ai-api
run-name: CI${{ github.run_number }}-${{ github.event.repository.name }}-${{ github.workflow }}_${{ github.ref_name }}
on:
  push:
    branches:
        - dev*
        - main
jobs:
    call-github-python-pytests-workflow:
        # {owner}/{repo}/.github/workflows/{filename}@{ref}
        uses: fereol023/pipelines_templates/.github/workflows/github-python-pytests.yml@main
        with:
            pythonVersion: 3.12
            hasSubmodules: true
    # call-github-python-linter-workflow:
    #     uses: fereol023/pipelines_templates/.github/workflows/github-python-linter.yml@main
    #     with: 
    #         pythonVersion: 3.12
    #     secrets:
    #         token: ${{ secrets.GITHUB_TOKEN }}